/*
    DIFERENÇAS ENTRE TIPOS
    ESCOLHER O TIPO CORRETO DE UM DADO PERMITE A BASE DE DADOS SER MAIS LEVE E RÁPIDA
    CHAR(n) POSSUI TAMANHO FIXO, PERMITE UMA MELHOR EFICIÊNCIA AO BANCO PORÉM SE ATENTAR AO ESPAÇO NÃO UTILIZADO
    VARCHAR(n) POSSUI TAMANHO VARIÁVEL, MAIOR PROCESSAMENTO

    ENUM: tipo utilizado permitir o agrupamento ou limitação de dados a partir dos comandos GROUP BY e COUNT
    no SQLSERVER utilizar CONSTRAINTS

    utilizar tipos numéricos(INT, FLOAT) somente para colunas onde serão realizados cálculos

    REGISTRO OU TUPLA: é o conjunto formado por colunas e linha
*/

/* 
    CRIAÇÃO DE BASE DE DADOS

    DELIMITADOR DE COMANDOS EM SQL ;
*/
CREATE DATABASE BASE_DE_DADOS;
USE BASE_DE_DADOS;
STATUS; --INFORMAÇÕES RELEVANTES

/*
    CRIAÇÃO  E CONSULTA DE TABELAS

    SE ATENTAR AO TUNING DA TABELA DE FORMA A ESCOLHER OS MELHORES TIPOS DE DADOS
    E ASSIM GARANTIR UMA MELHOR PERFORMANCE DE BUSCA E GERENCIAMENTO DA BASE
*/
CREATE TABLE TABELA_MODELO(
    CHARS_TAMANHO_VARIAVEL VARCHAR(20),
    CHARS_TAMANHO_FIXO CHAR(1),
    VALOR_INTEIRO INT,
    VALOR_DECIMAL FLOAT(10,2),
    /* BLOB BINARY LARGE OBJECT */
    FOTOS_E_DOCUMENTOS BLOB,
    TEXTO TEXT()
);

SHOW TABLES;
/* DESCRIBE TABLE */
DESC TABELA_MODELO;

/* 
    INSERÇÃO DE DADOS NA TABELA

    SÃO DUAS AS OPÇÕES: COMANDO COM COLUNAS EXPLÍCITAS E IMPLÍCITAS
*/
INSERT INTO TABELA_MODELO(COLUNA_1, COLUNA_2, COLUNA_3)
    VALUES('xpto', 'm', 123);

INSERT INTO TABELA_MODELO VALUES('xpto', 'm', 123);

/* 
    PROJEÇÃO: 'SELECT' sem 'WHERE'

    EVITAR comando 'SELECT * FROM TABELA' devido a quantidade de dados trafegados
    utilizar SEMPRE filtros quando possível para diminuir os dados trafegados
*/
SELECT * FROM TABELA;

SELECT COLUNA_1 AS ALIAS_1, COLUNA_2 AS ALIAS_2, NOW() AS FUNCAO FROM TABELA;

/* SELEÇÃO: 'SELECT' com 'WHERE' 'LIKE' '%' */
SELECT COLUNA_1, COLUNA_2
FROM TABELA
WHERE COLUNA_1 = 'ALGUM VALOR' AND COLUNA_2 = 'OUTRO VALOR' OR COLUNA_3 = 'VALOR DIFERENTE';
