--TRANSAÇÕES
BEGIN --MARCA O INÍCIO DE UMA TRANSAÇÃO
COMMIT --CASO AS ALTERAÇÕES ESTEJAM CORRETAS, ESTE COMANDO SALVA AS ALTERAÇÕES NO ARQUIVO .MDF
ROLLBACK --CASO SEJA NECESSÁRIO REVERTER AS ALTERAÇÕES
--CLAUSULA AMBIGUA: RESOLUÇÃO VIA PONTEIRO EM COLUNAS
--DDL DML DCL

/* DDL DATA DEFINITION LANGUAGE */
    CREATE DATABASE BASE
    GO --CRIAÇÃO DE PACOTES DE COMANDOS SQL PARA TRANSPORTE VIA TCP/IP E EXECUÇÃO NO SERVIDOR DE FORMA SÍNCRONA

    USE BASE
    GO

    CREATE TABLE TABELA(
        IDTABELA INT PRIMARY KEY IDENTITY(1,1), --INICIAR DO INT 1 E INCREMENTAR DE 1 EM 1
        C_CHAR CHAR(1) NOT NULL,
        C_DATE DATE,
        C_DATETIME DATETIME,
        C_UNIQUE VARCHAR(10) UNIQUE,
        C_MONEY MONEY
    )
    GO

    --CONSTRAINTS(RESTRIÇÕES) OU REGRAS DE TABELAS E RELACIONAMENTOS
    ALTER TABLE TABELA_ORIGEM
    ADD CONSTRAINT FK_ORIGEM_DESTINO
    FOREIGN KEY(C_IDORIGEM)
    REFERENCES TABELA_DESTINO(C_IDDESTINO)
    GO

    ALTER TABLE TABELA
    ADD CONSTRAINT CK_VALOR 
    CHECK (C_CHAR IN ('A', 'B'))
    GO

/* DML DATA MANIPULATION LANGUAGE */
    --SELECT
    SELECT A.COLUNA_1, B.COLUNA_2, ISNULL(C.COLUNA_3, 'SEM VALOR') AS 'ALIAS'
    FROM TABELA_1 A 
    INNER JOIN TABELA_2 B
    ON A.ID = B.ID_TABELA_1
    INNER JOIN TABELA_3 C
    ON A.ID = C.ID_TABELA_1
    WHERE A.C_TIPO = 'TIPO'
    GO

    --INSERT
    INSERT INTO TABELA(COLUNA_1, COLUNA_2)
    VALUES('VALOR', 101)
    GO

    --UPDATE
    UPDATE TABELA
    SET COLUNA = 'VALOR ATUALIZADO'
    WHERE ID_COLUNA = 1

    --DELETE
    DELETE FROM TABELA
    WHERE COLUNA BETWEEN 1 AND 101
    GO

/* TRIGGER */
    CREATE TRIGGER TR_TRIGGER
    ON TABELA
    UPDATE

/* CONVERSÕES */
    SELECT 1 + '1' --RES: 2
    GO

    SELECT '1' + '1' --RES: 11
    GO

/* STORED PROCEDURES */
    CREATE PROC SOMA
    AS
        SELECT 10 + 10 AS SOMA
    GO

    EXEC SOMA --EXECUÇÃO DA SP
    GO

    /* STORED PROCEDURES COM PARAMETROS */
    CREATE PROC CONTA @NUM1 INT, @NUM2 INT
    AS
        SELECT @NUM1 + NUM2
    GO

    EXEC CONTA 1, 2
    GO

    DROP PROC CONTA
    GO

    /* STORED PROCEDURES DO SISTEMA */
    SP_COLUMNS TABELA --EXIBIR ESTRUTURA DA TABELA, SIMILAR AO DESC DO MYSQL
    GO

    SP_HELP TABELA --EXIBIR ESTRUTURA DETALHADA DA TABELA INCLUINDO REFERÊNCIAS EXTERNAS A TABELA
    GO

/* FUNÇÕES ÚTEIS */
    SELECT GETDATE() AS DIA_HORA
    GO

    DATEDIFF() --RETRONA DIFERENÇA ENTRE DATAS EM UNIDADE DE MEDIDA DETERMINADO
    DATENAME() --RETORNA UM NOME
    DATEPART() --RETORNA UM INTEIRO
    DATEADD()
    CHARINDEX()

/* TSQL */
    --BLOCO DE EXECUÇÃO
    BEGIN
        PRINT 'MENSAGEM'
    END
    GO

    --BLOCO DE ATRIBUIÇÃO DE VARIÁVEIS
    DECLARE
    @VARIAVEL INT  
    BEGIN
        SET @VARIAVEL = 0
        PRINT @VARIAVEL
    END
    GO

    SELECT @VARIAVEL --**ERRO** DEVIDO A VARIAVEL ESTAR FORA DO ESCOPO