CREATE DATABASE BASE
GO --CRIAÇÃO DE PACOTES DE COMANDOS SQL PARA TRANSPORTE VIA TCP/IP E EXECUÇÃO NO SERVIDOR DE FORMA SÍNCRONA

USE BASE
GO

CREATE TABLE TABELA(
    IDTABELA INT IDENTITY
)
GO

BEGIN
COMMIT
ROLLBACK