--DDL DML DCL

/* DDL DATA DEFINITION LANGUAGE */
CREATE DATABASE BASE
GO --CRIAÇÃO DE PACOTES DE COMANDOS SQL PARA TRANSPORTE VIA TCP/IP E EXECUÇÃO NO SERVIDOR DE FORMA SÍNCRONA

USE BASE
GO

CREATE TABLE TABELA(
    IDTABELA INT PRIMARY KEY IDENTITY(1,1), --INICIAR DO INT 1 E INCREMENTAR DE 1 EM 1
    C_CHAR CHAR(1) NOT NULL,
    C_DATA DATE,
    C_UNIQUE VARCHAR(10) UNIQUE
)
GO

--CONSTRAINTS(RESTRIÇÕES) OU REGRAS
ALTER TABLE TABELA
ADD CONSTRAINT FK_ORIGEM_DESTINO
FOREIGN KEY(ID_ORIGEM) REFERENCES(ID_DESTINO)
GO

ALTER TABLE TABELA
ADD CONSTRAINT CK_VALOR CHECK (C_CHAR IN ('A', 'B'))
GO

--TRANSAÇÕES
BEGIN --MARCA O INÍCIO DE UMA TRANSAÇÃO
COMMIT --CASO AS ALTERAÇÕES ESTEJAM CORRETAS, ESTE COMANDO SALVA AS ALTERAÇÕES NO ARQUIVO .MDF
ROLLBACK --CASO SEJA NECESSÁRIO REVERTER AS ALTERAÇÕES

/* DML DATA MANIPULATION LANGUAGE */
INSERT INTO TABELA(COLUNA_1, COLUNA_2)
VALUES('', 0)
GO

/* STORED PROCEDURES DO SISTEMA */
SP_COLUMNS TABELA --EXIBIR ESTRUTURA DA TABELA, SIMILAR AO DESC DO MYSQL
GO

SP_HELP TABELA --EXIBIR ESTRUTURA DETALHADA DA TABELA INCLUINDO REFERÊNCIAS EXTERNAS A TABELA
GO